### PR TITLE
Feature: Reuse existing tab if possible

### PR DESCRIPTION
**Pull request by cannjeff**
Utilizes the openBrowser module and openChrome script from [react-dev-utils](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-dev-utils) in order to mimic the behavior of `create-react-app`.

Closes https://github.com/jasonmit/ember-open-browser/issues/1

### CODE REVIEW

**Comment by jasonmit** [comment]
@cannjeff I worry if the react-dev-util folks considers this module "public".  Would you be interested in pulling the module and its deps into ember-open-browser?

**Comment by cannjeff** [comment]
@jasonmit That was actually my first implementation of this, but adding react-dev-utils seemed like a cleaner approach. I am unsure how licensing works if we were to just pull the two files as well. As one carries the BSD 3 clause and the other an MIT. 

~~What gives you concern over the public nature of the module?~~

Edit: I looked a bit more at react-dev-utils once I'd had some coffee and found 
> Feel free to fork or copy and paste them into your projects if you’d like to have more control over them, or feel free to use the old versions.

I'll propose two options and let you pick.
1. Lock down the version of react-dev-utils used to the current 3.0.2 and remain as is
2. Pulling in the required module and its dependencies into ember-open-browser

Neither is all that much work, so just let me know which you'd prefer.

**Comment by jasonmit** [comment]
I would like to lean towards number 2.  Thanks again for taking this issue up!

**Comment by cannjeff** [comment]
@jasonmit I've pulled the required modules in. Please double check how I handled the different licenses. Feel free to make suggestions if this approach does not work.

**Comment by jasonmit** [comment]
@cannjeff RE: licensing.  I myself don't know - I'll need to dig around for other examples of projects that have attempted the same.

Thank you for carrying this forward, I'll version once I have clarification on the licensing.

**Comment by jasonmit** [comment]
After some research I believe this the way you annotated the files and the main LICENSE file is correct.  Thanks again.

**Comment by jasonmit** [comment]
Versioned as 0.5.0 - thanks!

I made some slight adjustments to use ember-cli's `ui.writeLine` instead of `console.log`, converted it to work with node 4.x, and moved everything pertaining to openBrowser into it's own directory with its own LICENSE.md.

**Pull request merged**
